### ISSUE TITLE
Application fails to start due to incompatible cuDNN version on Linux

### ISSUE THREAD

**Issue by yusufipk** [pinokiofactory/whisper-webui#1]
Hello,

I encountered an error while trying to install and run the script on Linux. Script ran fine but when I tried to start the app I got an error message.

```
Traceback (most recent call last):
File "[...]/app/app.py", line 10, in <module>
from modules.whisper.whisper_factory import WhisperFactory
File "[...]/app/modules/whisper/whisper_factory.py", line 6, in <module>
from modules.whisper.faster_whisper_inference import FasterWhisperInference
File "[...]/app/modules/whisper/faster_whisper_inference.py", line 4, in <module>
import torch
File "[...]/app/env/lib/python3.10/site-packages/torch/init.py", line 239, in <module>
from torch._C import * # noqa: F403
ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

To resolve this issue, I had to manually install the following packages in the Conda environment:

1. `conda install nccl`
2. `conda install cudnn=8.2`

After installing these packages, I was able to run the application successfully.

It appears that the application requires a specific version of cuDNN (8.x) which conflicts with the version installed by default (9.x). 

- OS: Linux

**Comment by jhj0517** [comment]
Hi. There's a version incompatibility between `faster-whisper` and `torch >= 2.4` now. 

I fixed it in https://github.com/jhj0517/Whisper-WebUI/pull/318 by downgrading `torch` to 2.3.1, so it should work fine if you re install the app.

I just tested on pinokio and it works fine in my environment.
